image: node:17

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts


# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
services: []

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/

optimize_tiles:
  stage: build
  script:
    - git clone https://github.com/thecodingmachine/map-optimizer
    - cd map-optimizer
    - npm install
    - cd ..
    - mkdir /tmp/dist
    - for i in **/*.json; do ./map-optimizer/bin/tile-optimizer -i $i -o /tmp/dist/$(dirname $i); done

deploy_maps:
  stage: deploy
  script:
    - ls -al /tmp/dist


