image: node:17

optimize_tiles:
  stage: build
  before_script:
    - apt-get update -y && apt-get install -y rsync
  script:
    - cd ..
    - rm -rf map-optimizer
    - git clone https://github.com/thecodingmachine/map-optimizer
    - cd map-optimizer
    - npm install
    - cd ../kosmos-weimar
    - mkdir dist
    - for i in **/*.json; do echo $i; ../map-optimizer/bin/tile-optimizer -i $i -o ./dist/$(dirname $i); rsync -av $(dirname $i)/ dist/$(dirname $i) --exclude="*.json" --exclude tiles ; done
  artifacts:
    expire_in: 1 hour
    untracked: true
    paths:
      - dist/

deploy_maps:
  before_script:
    - apt-get update -y && apt-get install openssh-client rsync -y
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  stage: deploy
  dependencies:
    - optimize_tiles
  script:
    - rsync -avz "-e ssh -o StrictHostKeyChecking=no -p$SSH_PORT" dist/ $SSH_USER@$SSH_HOST:/opt/workadventure-xce/contrib-mr/www/maps/kosmos-weimar/


