image: node:17

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

optimize_tiles:
  stage: build
  script:
    - git clone https://github.com/thecodingmachine/map-optimizer
    - cd map-optimizer
    - npm install
    - cd ..
    - mkdir /tmp/kosmos-weimar
    - for i in **/*.json; do ./map-optimizer/bin/tile-optimizer -i $i -o /tmp/kosmos-weimar/$(dirname $i); done
  artifacts:
    expire_in: 1 hour
    paths:
      - /tmp/kosmos-weimar

deploy_maps:
  stage: deploy
  dependencies:
    - optimize_tiles
  script:
    - ls -al /tmp/kosmos-weimar
    #- rsync -avz '-e ssh -o StrictHostKeyChecking=no -p$SSH_PORT' firmwares/ $SSH_HOST:/opt/workadventure-xce/contrib-mr/www/maps/


