image: node:17

optimize_tiles:
  stage: build
  script:
    - git clone https://github.com/thecodingmachine/map-optimizer
    - cd map-optimizer
    - npm install
    - cd ..
    - mkdir kosmos-weimar
    - for i in **/*.json; do ./map-optimizer/bin/tile-optimizer -i $i -o ./kosmos-weimar/$(dirname $i); rsync -av $(dirname $i)/ kosmos-weimar/$(dirname $i) --exclude="*.json" --exclude tiles ; done
  artifacts:
    expire_in: 1 hour
    untracked: true
    paths:
      - kosmos-weimar/

deploy_maps:
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client rsync -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  stage: deploy
  dependencies:
    - optimize_tiles
  script:
    - rsync -avz '-e ssh -o StrictHostKeyChecking=no -p$SSH_PORT' kosmos-weimar/ $SSH_USER@$SSH_HOST:/opt/workadventure-xce/contrib-mr/www/maps/kosmos-weimar/


